[[news]]
date = "2026-09-01"
content = "One paper accepted at NeurIPS 2026! 🎉"
tag = "Conference"

[[news]]
date = "2026-07-01"
content = "Two papers accepted at ACL 2026 (Main + Findings)! 🎉 🎉"
tag = "Conference"

[[news]]
date = "2026-02-04"
content = "Received the USC Viterbi/Annenberg Fellowship! 🎓"
tag = "Award"

[[news]]
date = "2026-02-04"
content = "Received the USC 2026 CCLS Seed Funding Award! 🏆"
tag = "Award"

[[news]]
date = "2025-12-02"
content = "See U Guys @ NeurIPS 2025🎉"
tag = "Conference"
