type = "card"
title = "Service"
description = "Professional service, reviewing, and community involvement."

[[items]]
title = "Conference on Neural Information Processing Systems (NeurIPS)"
subtitle = "Reviewer"
date = "2026"

[[items]]
title = "ACL Rolling Review (ARR)"
subtitle = "Reviewer"
date = "2026"

[[items]]
title = "ACM AI Summit"
subtitle = "Reviewer"
date = "2026"

[[items]]
title = "AAAI Conference on Artificial Intelligence (AAAI)"
subtitle = "Program Committee"
date = "2025, 2026"

[[items]]
title = "International Conference on Learning Representations (ICLR)"
subtitle = "Reviewer"
date = "2025"
